### ISSUE TITLE
老兄，有空时适配下最新2020.9.2的汉化啊！！

### ISSUE THREAD

**Issue by SmarTIGer** [hackxx/BurpSuiteCn#2]
原来的汉化文件在1.7下非常好用，在2.0前几个版本也可以，但最新版的就只能汉化部分了，请老兄有空时出手啊！

**Comment by hackxx** [comment]
提上日程了，近期就会发布最新版本。

**Comment by SmarTIGer** [comment]
> 提上日程了，近期就会发布最新版本。

感谢出手！！

**Comment by hackxx** [comment]
版本已更新！

**Comment by SmarTIGer** [comment]
感谢大佬，食用了之后，确实如兄弟说的，发送intruder有问题！
